name: Auto Release on a new Tag

# Controls when the workflow will run
on: 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # This will trigger the workflow for any tag starting with 'v' (e.g., v1.0.0, v2.1.0-beta)
  push:
    tags:
      - 'v*'

# Set the permission for this workflow
permissions:
  contents: write

  # ------------------------------------------------------------------------------------------------------------------------------------------------
  # Event `pull_request`: Compare the last commit of the main branch or last remote commit of the PR branch -> to the current commit of a PR branch.
  # ------------------------------------------------------------------------------------------------------------------------------------------------
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    
      # -----------------------------------------------------------------------------------------------------------
      # Find the current Release
      # -----------------------------------------------------------------------------------------------------------
      - name: Get Latest Release
        id: currentrelease
        uses: joutvhu/get-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          latest: true
          # Tag name starts with `v`
          pattern: '^v.*'
          # Including pre-release
          prerelease: true
          
      # -----------------------------------------------------------------------------------------------------------
      # Create the Changelog
      # -----------------------------------------------------------------------------------------------------------
      - name: Conventional Changelog Action
        id: changelog 
        uses: gableroux/generate-github-release-notes@v0.1.2
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           base_tag: ${{ github.event.release.tag_name }}
      #     base_tag: ${{ steps.currentrelease.outputs.tag_name }}
           head_tag: "${{ github.ref }}"
           repository: ${{ github.repository }}
           auto_detect_new_contributors: 'true'

      # -----------------------------------------------------------------------------------------------------------
      # Create the Release
      # -----------------------------------------------------------------------------------------------------------
      - name: Create the Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.changelog.outputs.notes }}
          draft: false
          prerelease: false
