# This is a workflow to watch for a merged PR with a specific
# Tag used to denote a version bump to a new `Y` version.  Once found,
# it will create a Tag and then Release based on that tag.

name: Automatic Tagging

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the "main" branch
  push:
    branches: [ "main" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run to find and do the tagging.
jobs:
  tag: 
    runs-on: ubuntu-latest
    steps: 
      -uses: actions/checkout@v2
      -name: Create the Tag
      run: |
        git config --label user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag -a "v${{ github.run_number }}" -m "v${{ github.run_number }}"
        git push origin "v${{ github.run_number }}
      -name: Create the Release
      uses: actions/create-release@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'v${{ github.run_number }}'
          release_name: 'v${{ github.run_number }}'
          body: 'Description of the changes in this release'
